import Config from "react-native-config";

const baseUrl = Config.API_URL_UAT;

const endurl: any = {
  LOGIN: `${baseUrl}/users-service/login/`,
  LOGOUT: `${baseUrl}/users-service/logout/`,
  REFRESHTOKEN:`${baseUrl}/users-service/get-access-token/`,
  FORGOTPASS: `${baseUrl}/users-service/reset/send-reset-password-code/`,
  RESETPASS: `${baseUrl}/users-service/reset/confirm-reset-password/`,
  COURSES: `${baseUrl}/course-code-service/courses/assigned_courses/`,
  GRADE: `${baseUrl}/course-code-service/courses/grade-list/`,
  COURSE_CODE_SERVICE: `${baseUrl}/course-code-service/courses/content/`,
  COMPONENTLIST: `${baseUrl}/course-code-service/courses/component-list/`,
  CONTENTLISTING: `${baseUrl}/course-code-service/courses/course-content-listing/`,
  GROUP: `${baseUrl}/users-service/groups-list/`,
  TIMETABLE: `${baseUrl}/roster-service/time_tables`,
  ASSIGNED_ASSESSMENT: `${baseUrl}/assessments-service/get-assign-assessment-list/`,
  GRADE_BOOK: `${baseUrl}/assessments-service/grade-book-list/`,
  TEACHER_ATTENDANCE: `${baseUrl}/roster-service/attendance-report-list`,
  CLASSLIST: `${baseUrl}/schools-service/school-classes/`,
  SUBJECTLIST: `${baseUrl}/course-code-service/courses/content/`,
  STUDENTLIST: `${baseUrl}/users-service/student-attendance-record`,
  COURSESLIST: `${baseUrl}/course-code-service/courses/`,
  ASIGNEDCLASSLIST: `${baseUrl}/schools-service/school-classes/`,
  ASSESMENTLIST: `${baseUrl}/assessments-service/my_assessments_list/`,
  CATEGORYLIST: `${baseUrl}/course-code-service/courses/content/`,
  GROUPDATALIST: `${baseUrl}/users-service/groups-list/`,
  STUDENT: `${baseUrl}/users-service/students/assigned/`,
  ASSIGNASSESMNET: `${baseUrl}/assessments-service/assign-assessment/`,
  TEACHER_COMPLETED_ASSESSMENT_LIST: `${baseUrl}/assessments-service/completed-assign-assessment-list/`,
  PARENTASSESSLIST: `${baseUrl}/assessments-service/student--assign-assessment-list/`,
  PARENT_CHILD_LIST: `${baseUrl}/users-service/parent-student-details/1/`,
  PARENT_ASSESS_COMPLETED: `${baseUrl}/assessments-service/completed-assign-assessment-student-list/`,
  VOLUME: `${baseUrl}/course-code-service/courses/volume-list/`,
  STUDENTDETAIL: `${baseUrl}/users-service/parent-student-details/`,
  ASSIGNASSIGNMENT: `${baseUrl}/assignments-service/student/assignment/list/`,
  TEACHER_ASSIGNMENT_LIST: `${baseUrl}/assignments-service/assignment/list/`,
  STUDENT_LIST: `${baseUrl}/assignments-service/assignment/assigned-students/`,
  CHANGE_STATUS: `${baseUrl}/assignments-service/assignments/teacher/`,
  TEACHER_COMPLETED_ASSIGNMENT_LIST: `${baseUrl}/assignments-service/assignment/list/`,
  TEACHER_COMPLETED_ASSIGNMENT_STUDENT_LIST: `${baseUrl}/assignments-service/assignment/assigned-students/`,
  TEACHER_ASSIGNMENT_RESULT: `${baseUrl}/assignments-service/assignment/student/`,
  STUDENT_NEW_ASSIGNMENT_LIST: `${baseUrl}/assignments-service/student/assignment/list/`,
  STUDENT_REPORT_ASSESSMENT_LIST: `${baseUrl}/assessments-service/completed-assign-assessment-student-list/`,
  STUDENT_REPORT_ASSIGNMENT_LIST: `${baseUrl}/assignments-service/student/assignment/list/`,
  STUDENT_ATTENDANCE: `${baseUrl}/roster-service/attendance-report-list`,
  STUDENT_SUBJECTLIST: `${baseUrl}/course-code-service/courses/content/`,
  STUDENT_STUDENTLIST: `${baseUrl}/users-service/student-attendance-record`,
  STUDENT_ASSESSMENTLIST: `${baseUrl}/assessments-service/assign-assessment-student-list/`,
  STUDENT_COMPLETED_ASSESSMENTLIST: `${baseUrl}/assessments-service/completed-assign-assessment-student-list/`,
  REPORT_SERVICES: `${baseUrl}/reports-service/performance_expectation/`,
  PARENT_REPORT_ASSESSMENT_LIST: `${baseUrl}/assessments-service/completed-assign-assessment-student-list/`,
  PARENT_REPORT_ASSIGNMENT_LIST: `${baseUrl}/assignments-service/student/assignment/list/`,
  TEACHER_COURSE_LISTING: `${baseUrl}/course-code-service/courses/course-content-listing/`,
  COMPONENT: `${baseUrl}/course-code-service/courses/content/?ordering=-created_at&limit=30&offset=0&selection=Component`,
  CLASSES: `${baseUrl}/schools-service/school-classes/teacher/assigned-class`,
  STUDENTLISTASSESSMENT: `${baseUrl}/users-service/students/assigned`,
  CREATE_ASSIGNMENT: `${baseUrl}/assignments-service/assignment/create/`,
  I_FRAME_ENDPOINT: `${baseUrl}/course-code-service/media/courses`,
  QUESTION_PRINT_I_FRAME: `${baseUrl}/assessments-service/print-assign-assessment`,
  SCHOOL_SERVICE_ATTENDENCE: `${baseUrl}/schools-service/schools/`,
};

export default endurl;
