import { StyleSheet } from "react-native";
import COLORS from "../../../../assests/color";
import { HEIGHT,WIDTH } from "../../../../locales/common";

export default StyleSheet.create({
  mainView: {
    height: HEIGHT,
    width: WIDTH,
    backgroundColor: COLORS.white,
    flex:1,
    flexDirection:'column',
    justifyContent: 'flex-start'
  },
  flatList: {
    // marginTop: '8%',
    // height:'75%',
  },
  textStyle: {
    fontSize: 14,
    fontWeight:'400',
    lineHeight:17,
    color: COLORS.blackCode,
    flexWrap:'wrap',
  },
  headerModal:{
    fontSize: 16,
    fontWeight:'600',
    lineHeight:17,
    paddingLeft:'3%',
    color: COLORS.blackCode,
    flexWrap:'wrap',
  },
  
  item: {
    paddingVertical: '5%',
    paddingHorizontal:'2%',
    marginLeft: '5%',
    width:'85%',
    flexDirection:'row',
    justifyContent:'flex-start',
    alignItems:'center',
  },
  itemText:{
    fontSize: 14,
    lineHeight:17,
    color: COLORS.blackCode,
    paddingLeft: '7%',
  },
  itemSeparator: {
    height: 1,
    width: "85%",
    marginLeft:'5%',
    backgroundColor: COLORS.listSeparatorColor,
  },
  iconStyle: {
    height: 35,
    width: 25,
    marginLeft: 15,
  },
  flatlistMain: {
    flex:1,
    margin:'4%',
    padding:'3%', 
    flexDirection:'column', 
    borderWidth:1, 
    borderColor: COLORS.InputBorderColor, 
    alignItems:'center',
    // height:'70%',
    // marginTop:'8%',
  },
  flatlistHeading: {
    flexDirection: 'row', 
    alignItems:'center',
    width:'100%',
    backgroundColor:COLORS.lightGrey, 
    padding:'4%', 
    // height:80,
  },
  tableHeadingTxt: {
    fontSize:14, 
    fontWeight:'500',
  },
  flatlisrRowView: {
    flexDirection: 'row', 
    alignItems:'center', 
    // height: 70,
    borderBottomWidth: 1, 
    borderBottomColor: COLORS.listSeparatorColor,
    padding:'4%', 
  },
  scoreView: { 
    width:'33%' , 
    height:60 , 
    alignItems:'center', 
    justifyContent:'center',
  },
  endAssignmentView:{
    alignSelf: "flex-end",
    marginRight: "5%",
    // marginTop: "2%",
    // marginBottom: "6%",
  },

  studentCountText: {
    fontSize: 14,
    fontWeight:'400',
    lineHeight:17,
    color: COLORS.Pink,
    flexWrap:'wrap',
  },
  totalstudentCountText: {
    fontSize: 14,
    fontWeight:'400',
    lineHeight:17,
    color: COLORS.blackCode,
    flexWrap:'wrap',
  },
  flatlistRowView: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    width: "100%",
    borderBottomColor: COLORS.listSeparatorColor,
  },
  noDataFound: {
    fontSize: 16,
    fontWeight: "600",
  },
  dropdown: {
    height: 40,
    borderColor: COLORS.InputBorderColor,
    borderWidth: 1,
    borderRadius: 5,
    marginTop: 16,
  },
  icon: {
    marginRight: 5,
  },
  label: {
    position: "absolute",
    backgroundColor: "white",
    left: 20,
    top: 5,
    zIndex: 999,
    paddingHorizontal: 5,
    fontSize: 13,
  },
  placeholderStyle: {
    fontSize: 14,
    paddingLeft: 10,
    fontWeight: "300",
    color: COLORS.colorBlack,
  },
  selectedTextStyle: {
    fontSize: 14,
    paddingLeft: 10,
    fontWeight: "300",
    color: COLORS.colorBlack,
  },
  column1View: {
    width: "34%",
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  submittedcolumn1View: {
    width: "30%",
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  column1Icon: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: "40%",
  },
  column1Data: {
    width: "33%",
   paddingHorizontal:'4%'
  },
  column2View: {
    width: "33%",
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  submittedcolumn2View: {
    width: "33%",
    flexDirection: "row",
    justifyContent: "flex-start",
    paddingHorizontal:'5%'
  },
  column2Icon: {
    flexDirection: "column",
    alignItems: "center",
    paddingLeft: "3%",
    justifyContent: "space-evenly",
  },
  column2Data: {
    width: "33%",
    paddingLeft: "2%",
  },
  column3View: {
    width: "33%",
    flexDirection: "row",
    justifyContent: "center",
    marginLeft: "3%",
  },
  column3Icon: {
    flexDirection: "column",
    alignItems: "center",
    paddingLeft: "13%",
    justifyContent: "space-between",
  },
  alignment: {
    alignItems: "center",
    justifyContent: "center",
    height: "50%",
  },
  cancelView: {
    alignItems: "flex-end",
    width: "100%",
  },
  LineView: {
    height: "1%",
    backgroundColor: COLORS.InputBorderColor,
    width: "97%",
    marginLeft: "2%",
    marginTop: "2%",
  },
  SubmitButton: {
    fontFamily: "CentraNo2-Medium",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 18,
    paddingLeft: "3%",
    color: COLORS.white,
    alignSelf: "center",
  },

  CancelButton: {
    fontFamily: "CentraNo2-Medium",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 18,
    paddingLeft: 5,
    color: COLORS.Pink,
    alignSelf: "center",
  },

  modal_alignment: {
    borderRadius: 2,
    height: "50%",
    width: "90%",
    alignSelf: "center",
    flexDirection: "column",
    backgroundColor: COLORS.white,
  },
  borderView: {
    width: "94%",
    height: 35,
    borderRadius: 4,
    borderColor: COLORS.transparentGrey,
    borderWidth: 1,
    justifyContent: "center",
    borderLeftColor: COLORS.leftBorder,
    borderLeftWidth: 3,
    margin: 10,
  },
  dropdownView: {
    width: "94%",
    marginLeft: 10,
    marginTop: 5,
  },
  buttonView: {
    marginTop: 38,
    width: "75%",
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  buttonStyle: {
    backgroundColor: COLORS.ThemeGreen,
    borderRadius: 4,
    height: 40,
  },
  changeStatusText: {
    fontSize: 12,
    fontWeight: "400",
    paddingTop: 20,
    paddingLeft: 10,
  },
  remarkText: {
    fontSize: 12,
    fontWeight: "300",
    paddingTop: 10,
    paddingLeft: 10,
  },
  remarkTextInput: {
    width: "94%",
    borderRadius: 5,
    marginLeft: 10,
    marginTop: 10,
    height: 90,
    fontFamily: "MaterialIcons-Regular",
  },
  noElementView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});
