import { StyleSheet } from "react-native";
import COLORS from "../../../../assests/color";
import { HEIGHT, WIDTH } from "../../../../locales/common";

export default StyleSheet.create({
  mainView: {
    height: HEIGHT,
    width: WIDTH,
    backgroundColor: COLORS.white,
  },
 
  itemText: {
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "400",
    color: COLORS.blackCode,
    paddingLeft: "2%",
  },
  marginView: {
    marginTop: 20,
    marginHorizontal: 10,
    flex: 1,
  },
  flatListMain: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  mainRenderView: {
    borderColor: COLORS.white,
    borderLeftWidth: 3,
    width: "100%",
    padding: "1%",
    height: 55,
    justifyContent: "center",
  },
  headerFirst: {
    margin: "3%",
    paddingHorizontal: "3%",
    flexDirection: "column",
    borderWidth: 1,
    borderColor: COLORS.InputBorderColor,
    alignItems: "center",
  },
  rowWiseView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.lightGrey,
    height: 65,
    marginTop: 20,
  },
  textView: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 17,
    textDecorationLine: "underline",
    paddingLeft: 2,
  },
  divideView: {
    width: 0.5,
    backgroundColor: COLORS.listSeparatorColor,
    height: "100%",
  },
  rowNumberWiseView: {
    flexDirection: "row",
    alignItems: "center",
    height: 42,
  },
  performanceView: {
    width: "40%",
    height: "100%",
    paddingRight: "10%",
    paddingLeft: "4%",
    borderColor: COLORS.listSeparatorColor,
    borderWidth: 1,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  fromHeaderView: {
    width: "15%",
    alignItems: "center",
    justifyContent: "center",
    borderColor: COLORS.listSeparatorColor,
    borderWidth: 1,
    height: "100%",
  },
  toHeaderView: {
    width: "15%",
    alignItems: "center",
    justifyContent: "center",
    borderColor: COLORS.listSeparatorColor,
    borderWidth: 1,
    height: "100%",
  },
  wrongHeaderView: {
    width: "15%",
    alignItems: "center",
    justifyContent: "center",
    borderColor: COLORS.listSeparatorColor,
    borderWidth: 1,
    height: "100%",
  },
  lastHeaderView: {
    width: "14%",
    alignItems: "center",
    justifyContent: "center",
    borderColor: COLORS.listSeparatorColor,
    borderWidth: 1,
    height: "100%",
  },
  performanceTextView: {
    width: "100%",
    height: "9%",
    flexDirection: "row",
    alignItems: "center",
  },
  performanceText: {
    fontSize: 14,
    fontWeight: "400",
  },
  boldText: {
    fontWeight: "500",
  },
  extraBoldText: {
    fontWeight: "600",
  },
  submitDtView: {
    height: "9%",
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.listSeparatorColor,
  },
  submitDtText: {
    fontSize: 18,
    fontWeight: "300",
    color: COLORS.colorBlack,
    textTransform: "capitalize",
    paddingRight: "1.5%",
  },
  teacherNameView: {
    height: "9%",
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.listSeparatorColor,
  },
  teacherNameText: {
    fontSize: 18,
    fontWeight: "300",
    color: COLORS.colorBlack,
    textTransform: "capitalize",
  },
  scoreView: {
    backgroundColor: COLORS.bgYellow,
    height: "15%",
    marginTop: "3%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  scoreViewText: {
    fontSize: 18,
    fontWeight: "500",
    alignSelf: "center",
    paddingVertical: 20,
    lineHeight: 22,
  },
  scorePercentText: {
    color: COLORS.lightRed,
    paddingHorizontal: "2%",
  },
  numQuestionsTxt: {
    fontSize: 14,
    fontWeight: "500",
  },
  itemSeparator: {
    height: 2.5,
    width: "90%",
    marginLeft: "6%",
    backgroundColor: COLORS.white,
  },
});
